### ISSUE TITLE
[Bug] Linked-in and Instagram icons/images are not visible

### ISSUE THREAD

**Issue by iatharva** [akshaaatt/akshaaatt#1]
Linked-in and Instagram icons/images are not visible.
The link might be broken or maybe a typo.

Hope this is helpful.
You can close the issue when it's solved :)

**Comment by akshaaatt** [comment]
Hi @iatharva thanks for reporting the issue! However, on my browser it seems to look fine and I confirmed by checking on two other devices as well.
<img width="1440" alt="Screenshot 2021-09-09 at 11 32 38 AM" src="https://user-images.githubusercontent.com/51470769/132631881-4d1e449d-1b45-426a-a15f-5357170e9c1a.png">

**Comment by iatharva** [comment]
Are you sure @akshaaatt ? 
(maybe try checking it after removing cache I would say)
### Here are the screenshots of the same from my two different devices:

![image](https://user-images.githubusercontent.com/25875102/132632322-08b0157e-89dc-464c-8aab-0c83a2d42fb5.png)
![WhatsApp Image 2021-09-09 at 11 40 27 AM](https://user-images.githubusercontent.com/25875102/132632449-5c406372-d8be-44a1-8535-b26aed95651b.jpeg)

**Comment by akshaaatt** [comment]
Thanks! I have updated the previous icons which went private and resolved this issue. Great! 💯

**Comment by iatharva** [comment]
Nice 👍🏼
